#--------------------------------------
# makefile.win32
# Windows-specific build configurations
# (supports 32-bit and 64-bit)
#--------------------------------------

# command line build tool
MSBUILD=msbuild.exe

# configuration
ifneq (,$(CHUCK_DEBUG))
CONFIG=Debug
CHUG_BIN=Debug/PlinkyRev.chug
else
CONFIG=Release
CHUG_BIN=Release/PlinkyRev.chug
endif

# targets
default: $(CHUG_BIN)

$(CHUG_BIN): 
	$(MSBUILD) /p:Configuration=$(CONFIG) /property:Platform=x64
	cp ./x64/Release/PlinkyRev.chug ./

clean:
	$(MSBUILD) /p:Configuration=$(CONFIG) /t:Clean
	rm PlinkyRev.chug

